import { ConflictError, NotFoundError } from '@core/errors/app-error';
import { categoryRepository } from './category.repository';
import type {
  CreateCategoryInput,
  ICategoryRepository,
  SafeCategory,
  UpdateCategoryInput,
} from './category.types';

/**
 * Category business rules:
 *   - names are unique (case-insensitive),
 *   - a category with products cannot be deleted (would orphan products).
 * The UUID (`uniqueId`) is generated by the DB default — the app never has to.
 */
export class CategoryService {
  constructor(private readonly repo: ICategoryRepository) {}

  getAll(): Promise<SafeCategory[]> {
    return this.repo.findManyActive();
  }

  async getById(id: number): Promise<SafeCategory> {
    const category = await this.repo.findActiveById(id);
    if (!category) throw new NotFoundError('Category');
    return category;
  }

  async create(input: CreateCategoryInput): Promise<SafeCategory> {
    if (await this.repo.existsByName(input.name)) {
      throw new ConflictError('A category with this name already exists');
    }
    return this.repo.create({ name: input.name });
  }

  async update(id: number, input: UpdateCategoryInput): Promise<SafeCategory> {
    await this.getById(id);
    if (input.name && (await this.repo.existsByName(input.name, id))) {
      throw new ConflictError('A category with this name already exists');
    }
    return this.repo.update(id, input.name !== undefined ? { name: input.name } : {});
  }

  async remove(id: number): Promise<void> {
    await this.getById(id);
    // Business rule: refuse to delete a category that still has products.
    // (The DB FK also enforces this with onDelete: Restrict — defence in depth.)
    const productCount = await this.repo.countActiveProducts(id);
    if (productCount > 0) {
      throw new ConflictError(
        `Cannot delete category: ${productCount} product(s) still reference it`,
      );
    }
    await this.repo.softDelete(id);
  }
}

export const categoryService = new CategoryService(categoryRepository);
